# Generated by Django 4.1.2 on 2023-08-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link2dot5_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
    ]
