# Generated by Django 4.1.2 on 2023-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link2dot5_app', '0002_deposit_transaction_id_alter_member_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
