# Generated by Django 4.1.2 on 2023-08-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link2dot5_app', '0003_alter_deposit_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanappn',
            name='loan_officer',
        ),
        migrations.RemoveField(
            model_name='loanappn',
            name='member',
        ),
        migrations.RemoveField(
            model_name='loanpay',
            name='approvedloan',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='loan',
        ),
        migrations.DeleteModel(
            name='ApprovedLoan',
        ),
        migrations.DeleteModel(
            name='LoanAppn',
        ),
        migrations.DeleteModel(
            name='LoanPay',
        ),
        migrations.DeleteModel(
            name='LoanPayment',
        ),
    ]
