# Generated by Django 4.1.2 on 2023-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link2dot5_app', '0004_remove_loanappn_loan_officer_remove_loanappn_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('date_of_income', models.DateTimeField()),
                ('receipt', models.ImageField(blank=True, upload_to='income/%Y/%m/%d')),
            ],
        ),
    ]
