# Generated by Django 4.1.2 on 2023-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link2dot5_app', '0005_otherincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
