# Generated by Django 4.1.2 on 2023-08-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='telephone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
