# Generated by Django 4.1.2 on 2023-08-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0002_loanapplication_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='telephone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='loans_app.reviewedloan'),
        ),
    ]
