# Generated by Django 4.1.2 on 2023-08-16 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0003_alter_loanapplication_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewedloan',
            name='date_disbursed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 16, 9, 20, 2, 446765, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewedloan',
            name='interest_rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
