# Generated by Django 4.1.2 on 2023-08-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0004_reviewedloan_date_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_app.reviewedloan'),
        ),
        migrations.AlterField(
            model_name='reviewedloan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewedloan',
            name='interest_rate',
            field=models.PositiveIntegerField(),
        ),
    ]
