# Generated by Django 4.1.2 on 2023-08-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0005_loanapplication_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
