# Generated by Django 4.1.2 on 2023-08-21 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0009_rename_date_disbursed_reviewedloan_review_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='reviewedloan',
            name='loan_application',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='disbursed_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_period',
            new_name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='disbursed_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_id',
            field=models.CharField(default='moo1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_name',
            field=models.CharField(default='moo1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_name',
            field=models.CharField(default='moo1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor1_ID',
            field=models.CharField(default='moo1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor2_ID',
            field=models.CharField(default='moo1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default='moo1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 8, 30, 44, 519146, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='telephone',
            field=models.PositiveIntegerField(default=22222),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanPayment',
        ),
        migrations.DeleteModel(
            name='ReviewedLoan',
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_app.loan'),
        ),
    ]
