# Generated by Django 4.1.2 on 2023-08-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0010_installment_remove_loanpayment_loan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
    ]
