# Generated by Django 4.1.2 on 2023-08-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0011_remove_loan_accepted_remove_loan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='guarantor1_ID',
            new_name='guarantor1',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='guarantor2_ID',
            new_name='guarantor2',
        ),
    ]
