# Generated by Django 4.1.2 on 2023-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0013_alter_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
