# Generated by Django 4.1.2 on 2023-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0014_loan_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], default='approved', max_length=20),
        ),
    ]
