# Generated by Django 4.1.2 on 2023-08-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0015_loan_is_reviewed_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=20),
        ),
    ]
